name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django-version:
          - ">=3.0,<4.0"
          - ">=4.0,<5.0"
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"  # no compatible pysam yet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Django dependency
        run: |
          pip install "Django${{ matrix.django-version }}"

      - name: Install this library via pip
        run: |
          pip install -e .

      - name: Run the tests
        run: |
          cd example-project
          python manage.py test djangoplugins

      - name: Check that the migrations work
        run: |
          cd example-project
          python manage.py makemigrations
          python manage.py migrate
          python manage.py syncplugins
